// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Plate struct {
	Plate string `json:"plate"`
}

type TruckCar struct {
	ID    int        `json:"id"`
	Main  *TruckMain `json:"main"`
	Plate string     `json:"plate"`
}

type TruckMain struct {
	ID         int     `json:"id"`
	StatusCode int     `json:"statusCode"`
	StatusDesc string  `json:"statusDesc"`
	Spsj       *string `json:"spsj"`
}
